import '../styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

const prefix = '/my-next-app'

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href={prefix + "/favicon.ico"} />
    </Head>

    <Component {...pageProps} />
  </>
}

export default MyApp
